language: php
sudo: false
php:
  - 7.2
  - 5.6

env:
  # WP latest stable:
  - WP_VERSION=latest
  # WP nightly:
  - WP_VERSION=nightly

matrix:
  fast_finish: true

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

before_install:
  # set up WP install
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - mkdir -p $WP_DEVELOP_DIR
  - git clone --depth=1 --branch $WP_VERSION git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
  # set up tests config
  - cd $WP_DEVELOP_DIR
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
  - sed -i "s/yourusernamehere/root/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php
  # set up database
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
  - cd $TRAVIS_BUILD_DIR

install:
  - git config --global user.email "paul@hmn.md"
  - git config --global user.name "Paul de Wouters"

notifications:
  email: false
  slack:
    secure: ZyXhKGpR/VtggG3vcCaZ+50HBn4STi2fOvMKrmZaeS44s+j6lhkYt7qT1UeU1o2Vox2WCrdqfZqT370f4OV3izAgf7Ln+vIYxZvCywL2Cyt4YbHVPX0pMwuDuAW6a1zG5oP87CFZh9YYCHQ6HfX9ATKtnqiuMFx/SjOcD1Yb4Lk=

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer self-update
  - composer install --no-interaction

script:
  - cd $TRAVIS_BUILD_DIR
  - |
    if [[ "$TRAVIS_PHP_VERSION" == "5.6" && "$WP_VERSION" == "master" && "$WP_MULTISITE" == "0" ]] ; then
        phpunit --coverage-clover=coverage.xml
    else
        phpunit
    fi

git:
  depth: 1
